export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';
export const CHANGE_SEARCHTYPE = 'CHANGE_SEARCHTYPE';

export const REQUEST_HOSTELS_PENDING = 'REQUEST_HOSTELS_PENDING';
export const REQUEST_HOSTELS_SUCCESS = 'REQUEST_HOSTELS_SUCCESS';
export const REQUEST_HOSTELS_FAILED = 'REQUEST_HOSTELS_FAILED';
